[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg", "mio_unsupported_force_poll_poll",
    "--cfg", "espidf_time64",
    "-C", "default-linker-libraries",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v5.1.2"
ESP_LOG = "info"
